### ISSUE TITLE
Escape Slack messages

### ISSUE THREAD

**Issue by djmetzle** [iFixit/PullBot#10]
A recent PR i opened was posted to slack with some bad formatting:
![image](https://user-images.githubusercontent.com/6876047/127677988-99985254-f985-4712-b9c2-12d8e2db137f.png)

Original PR link: https://github.com/iFixit/server-templates/pull/3090

It looks like the `>` character in the PR title broke the slack message formatting.

We should try to do some escaping, or maybe strip out certain special characters, from the github input?

CC @addison-grant

**Comment by addison-grant** [comment]
Another PR that broke it https://github.com/iFixit/ifixit/pull/39699
![image](https://user-images.githubusercontent.com/10889879/132415657-36b2ed86-7dca-415d-b27b-d24d1d174a94.png)
